### ISSUE TITLE
\textemdash is not replaced 

### ISSUE THREAD

**Issue by getreu** [asciidoctor/asciidoctor-bibtex#11]
## Zoteros output:
```
@article{guo2009,
  title = {Validation and Verification of Computer Forensic Software tools\textemdash{}{{Searching Function}}},
  volume = {6},
  issn = {17422876},
  doi = {10.1016/j.diin.2009.06.015},
  language = {en},
  timestamp = {2016-06-13T16:44:17Z},
  urldate = {2016-06-13},
  journal = {Digital Investigation},
  author = {Guo, Yinghua and Slay, Jill and Beckett, Jason},
  month = sep,
  year = {2009},
  pages = {S12--S22}
}
```

## How it is rendered

2. Y. Guo, J. Slay, and J. Beckett, “Validation and Verification of Computer Forensic
Software tools\textemdashSearching Function,” Digital Investigation, vol. 6, pp.
S12–S22, Sep. 2009.

Please note the `\textemdash`

**Comment by ProgramFan** [comment]
Thanks, @getreu . I will look into this.

**Comment by ProgramFan** [comment]
Fixed by  	cdc0b39. Would you please try it, @getreu ? You can build a gem from the source code. I am planning to release a new gem when the internal refactoring is done, but not as soon as possible.

**Comment by getreu** [comment]
Hello @ProgramFan ,

it complies and installs nicely, but it get the following runtime error:

```
asciidoctor     -r asciidoctor-bibtex -r asciidoctor-diagram -b xhtml5 "Some.adoc"
/var/lib/gems/2.1.0/gems/asciidoctor-bibtex-0.3.0.dev/lib/asciidoctor-bibtex.rb:23:in `require_relative': /var/lib/gems/2.1.0/gems/asciidoctor-bibtex-0.3.0.dev/lib/asciidoctor-bibtex/processor.rb:1
6: syntax error, unexpected ',', expecting ')' (SyntaxError)
...ns.bibfile, :filter => :latex), options.links, options.style...
...                               ^
/var/lib/gems/2.1.0/gems/asciidoctor-bibtex-0.3.0.dev/lib/asciidoctor-bibtex/processor.rb:16: syntax error, unexpected ',', expecting :: or '[' or '.'
...s.numeric_in_appearance_order?, options.output, options.bibf...
...                               ^
/var/lib/gems/2.1.0/gems/asciidoctor-bibtex-0.3.0.dev/lib/asciidoctor-bibtex/processor.rb:16: syntax error, unexpected '\n', expecting '='
        from /var/lib/gems/2.1.0/gems/asciidoctor-bibtex-0.3.0.dev/lib/asciidoctor-bibtex.rb:23:in `<top (required)>'
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:135:in `require'
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:144:in `require'
        from /var/lib/gems/2.1.0/gems/asciidoctor-1.5.4/lib/asciidoctor/cli/options.rb:219:in `block in parse!'
        from /var/lib/gems/2.1.0/gems/asciidoctor-1.5.4/lib/asciidoctor/cli/options.rb:217:in `each'
        from /var/lib/gems/2.1.0/gems/asciidoctor-1.5.4/lib/asciidoctor/cli/options.rb:217:in `parse!'
        from /var/lib/gems/2.1.0/gems/asciidoctor-1.5.4/lib/asciidoctor/cli/options.rb:33:in `parse!'
        from /var/lib/gems/2.1.0/gems/asciidoctor-1.5.4/lib/asciidoctor/cli/invoker.rb:21:in `initialize'
        from /var/lib/gems/2.1.0/gems/asciidoctor-1.5.4/bin/asciidoctor:12:in `new'
        from /var/lib/gems/2.1.0/gems/asciidoctor-1.5.4/bin/asciidoctor:12:in `<top (required)>'
        from /usr/local/bin/asciidoctor:23:in `load'
        from /usr/local/bin/asciidoctor:23:in `<main>'
```

**Comment by ProgramFan** [comment]
Sorry. Fixed in master.

**Comment by getreu** [comment]
It works, thank you!
