### ISSUE TITLE
Error when loading asciidoctor-bibtex with latest asciidoctor 1.5.6

### ISSUE THREAD

**Issue by prudhomm** [asciidoctor/asciidoctor-bibtex#24]
```
asciidoctor: WARNING: gem 'thread_safe' is not installed. This gem is recommended when registering custom converters.
--
  | /usr/lib/ruby/vendor_ruby/bundler/runtime.rb:94:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'asciidoctor-bibtex'. (Bundler::GemRequireError)
  | Gem Load Error is: undefined method `positional_attributes' for AsciidoctorBibtex::Asciidoctor::BibliographyBlockMacro:Class
  | Did you mean?  positional_attrs
  | name_positional_attributes
  | Backtrace for gem load error is:
  | /var/lib/gems/2.3.0/gems/asciidoctor-bibtex-0.3.0/lib/asciidoctor-bibtex/bibextension.rb:55:in `<class:BibliographyBlockMacro>'
  | /var/lib/gems/2.3.0/gems/asciidoctor-bibtex-0.3.0/lib/asciidoctor-bibtex/bibextension.rb:52:in `<module:Asciidoctor>'
  | /var/lib/gems/2.3.0/gems/asciidoctor-bibtex-0.3.0/lib/asciidoctor-bibtex/bibextension.rb:21:in `<module:AsciidoctorBibtex>'
  | /var/lib/gems/2.3.0/gems/asciidoctor-bibtex-0.3.0/lib/asciidoctor-bibtex/bibextension.rb:20:in `<top (required)>'
  | /var/lib/gems/2.3.0/gems/asciidoctor-bibtex-0.3.0/lib/asciidoctor-bibtex/asciidoctor.rb:2:in `require_relative'
  | /var/lib/gems/2.3.0/gems/asciidoctor-bibtex-0.3.0/lib/asciidoctor-bibtex/asciidoctor.rb:2:in `<top (required)>'
  | /var/lib/gems/2.3.0/gems/asciidoctor-bibtex-0.3.0/lib/asciidoctor-bibtex.rb:11:in `require_relative'
  | /var/lib/gems/2.3.0/gems/asciidoctor-bibtex-0.3.0/lib/asciidoctor-bibtex.rb:11:in `<top (required)>'
  | /usr/lib/ruby/vendor_ruby/bundler/runtime.rb:91:in `require'
  | /usr/lib/ruby/vendor_ruby/bundler/runtime.rb:91:in `block (2 levels) in require'
  | /usr/lib/ruby/vendor_ruby/bundler/runtime.rb:86:in `each'
  | /usr/lib/ruby/vendor_ruby/bundler/runtime.rb:86:in `block in require'
  | /usr/lib/ruby/vendor_ruby/bundler/runtime.rb:75:in `each'
  | /usr/lib/ruby/vendor_ruby/bundler/runtime.rb:75:in `require'
  | /usr/lib/ruby/vendor_ruby/bundler.rb:106:in `require'
  | /var/lib/gems/2.3.0/gems/jekyll-3.5.0/lib/jekyll/plugin_manager.rb:49:in `require_from_bundler'
  | /var/lib/gems/2.3.0/gems/jekyll-3.5.0/exe/jekyll:9:in `<top (required)>'
  | /usr/local/bin/jekyll:22:in `load'
  | /usr/local/bin/jekyll:22:in `<main>'
  | Bundler Error Backtrace:
  | from /usr/lib/ruby/vendor_ruby/bundler/runtime.rb:90:in `block (2 levels) in require'
  | from /usr/lib/ruby/vendor_ruby/bundler/runtime.rb:86:in `each'
  | from /usr/lib/ruby/vendor_ruby/bundler/runtime.rb:86:in `block in require'
  | from /usr/lib/ruby/vendor_ruby/bundler/runtime.rb:75:in `each'
  | from /usr/lib/ruby/vendor_ruby/bundler/runtime.rb:75:in `require'
  | from /usr/lib/ruby/vendor_ruby/bundler.rb:106:in `require'
  | from /var/lib/gems/2.3.0/gems/jekyll-3.5.0/lib/jekyll/plugin_manager.rb:49:in `require_from_bundler'
  | from /var/lib/gems/2.3.0/gems/jekyll-3.5.0/exe/jekyll:9:in `<top (required)>'
  | from /usr/local/bin/jekyll:22:in `load'
  | from /usr/local/bin/jekyll:22:in `<main>'
```

**Comment by ProgramFan** [comment]
I will look into this.

**Comment by shahryareiv** [comment]
@ProgramFan 
Just to remind that the new fix has not been applied to the "cite-in-prose" branch yet.

**Comment by shahryareiv** [comment]
Any progress for cite-in-prose ?
