### ISSUE TITLE
Problem with asciidoctor-bibtex-cite-in-prose after update to Asciidoc 1.5.6

### ISSUE THREAD

**Issue by shahryareiv** [asciidoctor/asciidoctor-bibtex#25]
When calling

```
asciidoctor  --require "/here/other_modules/asciidoctor-bibtex-cite-in-prose/lib/asciidoctor-bibtex.rb"  -a bibtex-file=library.bib -a bibtex-style=apa -a bibtex-order=appearance -a bibtex-format=asciidoc --backend html5  -a imagesdir=html_images  -a stylesheet=my.css  -a stylesdir=html_libs  -a linkcss  -a docinfo1  -a pagenums  -a nofooter  -a lang=en  --doctype article "test.adoc.txt" --out-file="test.adoc.html"
```
I got
```
/here/other_modules/asciidoctor-bibtex-cite-in-prose/lib/asciidoctor-bibtex/bibextension.rb:55:in `<class:BibliographyBlockMacro>': undefined method `positional_attributes' for AsciidoctorBibtex::Asciidoctor::BibliographyBlockMacro:Class (NoMethodError)
	from /here/other_modules/asciidoctor-bibtex-cite-in-prose/lib/asciidoctor-bibtex/bibextension.rb:52:in `<module:Asciidoctor>'
	from /here/other_modules/asciidoctor-bibtex-cite-in-prose/lib/asciidoctor-bibtex/bibextension.rb:21:in `<module:AsciidoctorBibtex>'
	from /here/other_modules/asciidoctor-bibtex-cite-in-prose/lib/asciidoctor-bibtex/bibextension.rb:20:in `<top (required)>'
	from /here/other_modules/asciidoctor-bibtex-cite-in-prose/lib/asciidoctor-bibtex/asciidoctor.rb:2:in `require_relative'
	from /here/other_modules/asciidoctor-bibtex-cite-in-prose/lib/asciidoctor-bibtex/asciidoctor.rb:2:in `<top (required)>'
	from /here/other_modules/asciidoctor-bibtex-cite-in-prose/lib/asciidoctor-bibtex.rb:11:in `require_relative'
	from /here/other_modules/asciidoctor-bibtex-cite-in-prose/lib/asciidoctor-bibtex.rb:11:in `<top (required)>'
	from /Users/sei/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/sei/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/sei/.rvm/gems/ruby-2.2.2/gems/asciidoctor-1.5.6/lib/asciidoctor/cli/options.rb:230:in `block in parse!'
	from /Users/sei/.rvm/gems/ruby-2.2.2/gems/asciidoctor-1.5.6/lib/asciidoctor/cli/options.rb:228:in `each'
	from /Users/sei/.rvm/gems/ruby-2.2.2/gems/asciidoctor-1.5.6/lib/asciidoctor/cli/options.rb:228:in `parse!'
	from /Users/sei/.rvm/gems/ruby-2.2.2/gems/asciidoctor-1.5.6/lib/asciidoctor/cli/options.rb:33:in `parse!'
	from /Users/sei/.rvm/gems/ruby-2.2.2/gems/asciidoctor-1.5.6/lib/asciidoctor/cli/invoker.rb:22:in `initialize'
	from /Users/sei/.rvm/gems/ruby-2.2.2/gems/asciidoctor-1.5.6/bin/asciidoctor:12:in `new'
	from /Users/sei/.rvm/gems/ruby-2.2.2/gems/asciidoctor-1.5.6/bin/asciidoctor:12:in `<top (required)>'
	from /Users/sei/.rvm/gems/ruby-2.2.2/bin/asciidoctor:23:in `load'
	from /Users/sei/.rvm/gems/ruby-2.2.2/bin/asciidoctor:23:in `<main>'
	from /Users/sei/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `eval'
	from /Users/sei/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `<main>'

    at checkExecSyncError (child_process.js:588:13)
    at execSync (child_process.js:628:13)
    at /here/gulpfile.js:1111:5
    at Stream.modifyFile (/here/node_modules/gulp-tap/lib/tap.js:69:11)
    at Stream.stream.write (/here/node_modules/through/index.js:26:11)
    at Newer.ondata (_stream_readable.js:628:20)
    at emitOne (events.js:115:13)
    at Newer.emit (events.js:210:7)
    at addChunk (_stream_readable.js:252:12)
    at readableAddChunk (_stream_readable.js:239:11)
```

**Comment by ProgramFan** [comment]
The same problem as #24. See #24 for progress.

**Comment by ProgramFan** [comment]
Solved.
